import type { NextApiRequest, NextApiResponse } from 'next';
import { IChat } from '@/typings/db';

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<IChat[]>,
) {
  res.statusCode = 200;
  res.json([
    {
      id: 1,
      UserId: 1,
      User: {
        userId: 1,
        email: 'jiwlee@student.42.fr',
        intraUsername: 'jiwlee',
        nickname: 'jiwlee',
        imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
        status: 'online',
        experience: 42,
        rankId: 1,
        banDate: null,
        isStatusPublic: true,
        isHistoryPublic: true,
        createdAt: '2021-10-11T06:28:44.899Z',
        lastModifiedAt: '2021-10-11T06:28:44.899Z',
        deletedAt: null,
      },
      content: '안녕하세요',
      createdAt: new Date(),
      ChannelId: 2,
      Channel: {
        id: 2,
        name: 'random',
        private: false,
      },
    },
    {
      id: 1,
      UserId: 1,
      User: {
        userId: 1,
        email: 'jiwlee@student.42.fr',
        intraUsername: 'jiwlee',
        nickname: 'jiwlee',
        imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
        status: 'online',
        experience: 42,
        rankId: 1,
        banDate: null,
        isStatusPublic: true,
        isHistoryPublic: true,
        createdAt: '2021-10-11T06:28:44.899Z',
        lastModifiedAt: '2021-10-11T06:28:44.899Z',
        deletedAt: null,
      },
      content: '안녕',
      createdAt: new Date(),
      ChannelId: 2,
      Channel: {
        id: 2,
        name: 'random',
        private: false,
      },
    },
    {
      id: 1,
      UserId: 1,
      User: {
        userId: 1,
        email: 'jiwlee@student.42.fr',
        intraUsername: 'jiwlee',
        nickname: 'jiwlee',
        imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
        status: 'online',
        experience: 42,
        rankId: 1,
        banDate: null,
        isStatusPublic: true,
        isHistoryPublic: true,
        createdAt: '2021-10-11T06:28:44.899Z',
        lastModifiedAt: '2021-10-11T06:28:44.899Z',
        deletedAt: null,
      },
      content: 'hihi',
      createdAt: new Date(),
      ChannelId: 2,
      Channel: {
        id: 2,
        name: 'random',
        private: false,
      },
    },
  ]);
}
