import type { NextApiRequest, NextApiResponse } from 'next';
import { IUser } from '@/typings/db';

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<IUser[]>,
) {
  res.statusCode = 200;
  // res.json([
  //   {
  //     userId: 1,
  //     email: 'jiwlee@student.42.fr',
  //     intraUsername: 'jiwlee',
  //     nickname: 'jiwlee',
  //     imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //     status: 'online',
  //     experience: 42,
  //     rankId: 1,
  //     banDate: null,
  //     isStatusPublic: true,
  //     isHistoryPublic: true,
  //     createdAt: '2021-10-11T06:28:44.899Z',
  //     lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //     deletedAt: null,
  //   },
  //   {
  //     userId: 2,
  //     email: 'cbaek@student.42.fr',
  //     intraUsername: 'cbaek',
  //     nickname: 'cbaek',
  //     imagePath: 'https://cdn.intra.42.fr/users/cbaek.jpg',
  //     status: 'online',
  //     experience: 42,
  //     rankId: 2,
  //     banDate: null,
  //     isStatusPublic: true,
  //     isHistoryPublic: true,
  //     createdAt: '2021-10-11T06:28:44.899Z',
  //     lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //     deletedAt: null,
  //   },
  //   {
  //     userId: 3,
  //     email: 'kycho@student.42.fr',
  //     intraUsername: 'kycho',
  //     nickname: 'kycho',
  //     imagePath: 'https://cdn.intra.42.fr/users/kycho.jpg',
  //     status: 'online',
  //     experience: 42,
  //     rankId: 3,
  //     banDate: null,
  //     isStatusPublic: true,
  //     isHistoryPublic: true,
  //     createdAt: '2021-10-11T06:28:44.899Z',
  //     lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //     deletedAt: null,
  //   },
  //   {
  //     userId: 4,
  //     email: 'mykang@student.42.fr',
  //     intraUsername: 'mykang',
  //     nickname: 'mykang',
  //     imagePath: 'https://cdn.intra.42.fr/users/mykang.jpg',
  //     status: 'online',
  //     experience: 42,
  //     rankId: 4,
  //     banDate: null,
  //     isStatusPublic: true,
  //     isHistoryPublic: true,
  //     createdAt: '2021-10-11T06:28:44.899Z',
  //     lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //     deletedAt: null,
  //   },
  //   {
  //     userId: 5,
  //     email: 'sucho@student.42.fr',
  //     intraUsername: 'sucho',
  //     nickname: 'sucho',
  //     imagePath: 'https://cdn.intra.42.fr/users/sucho.jpg',
  //     status: 'offline',
  //     experience: 42,
  //     rankId: 5,
  //     banDate: null,
  //     isStatusPublic: true,
  //     isHistoryPublic: true,
  //     createdAt: '2021-10-11T06:28:44.899Z',
  //     lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //     deletedAt: null,
  //   },
  // {
  //   userId: 6,
  //   email: 'jiwlee@student.42.fr',
  //   intraUsername: 'jiwlee',
  //   nickname: 'jiwlee',
  //   imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //   status: 'online',
  //   experience: 42,
  //   rankId: 1,
  //   banDate: null,
  //   isStatusPublic: true,
  //   isHistoryPublic: true,
  //   createdAt: '2021-10-11T06:28:44.899Z',
  //   lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //   deletedAt: null,
  // },
  // {
  //   userId: 7,
  //   email: 'jiwlee@student.42.fr',
  //   intraUsername: 'jiwlee',
  //   nickname: 'jiwlee',
  //   imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //   status: 'online',
  //   experience: 42,
  //   rankId: 1,
  //   banDate: null,
  //   isStatusPublic: true,
  //   isHistoryPublic: true,
  //   createdAt: '2021-10-11T06:28:44.899Z',
  //   lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //   deletedAt: null,
  // },
  // {
  //   userId: 8,
  //   email: 'jiwlee@student.42.fr',
  //   intraUsername: 'jiwlee',
  //   nickname: 'jiwlee',
  //   imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //   status: 'online',
  //   experience: 42,
  //   rankId: 1,
  //   banDate: null,
  //   isStatusPublic: true,
  //   isHistoryPublic: true,
  //   createdAt: '2021-10-11T06:28:44.899Z',
  //   lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //   deletedAt: null,
  // },
  // {
  //   userId: 9,
  //   email: 'jiwlee@student.42.fr',
  //   intraUsername: 'jiwlee',
  //   nickname: 'jiwlee',
  //   imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //   status: 'online',
  //   experience: 42,
  //   rankId: 1,
  //   banDate: null,
  //   isStatusPublic: true,
  //   isHistoryPublic: true,
  //   createdAt: '2021-10-11T06:28:44.899Z',
  //   lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //   deletedAt: null,
  // },
  // {
  //   userId: 10,
  //   email: 'jiwlee@student.42.fr',
  //   intraUsername: 'jiwlee',
  //   nickname: 'jiwlee',
  //   imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //   status: 'online',
  //   experience: 42,
  //   rankId: 1,
  //   banDate: null,
  //   isStatusPublic: true,
  //   isHistoryPublic: true,
  //   createdAt: '2021-10-11T06:28:44.899Z',
  //   lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //   deletedAt: null,
  // },
  // {
  //   userId: 11,
  //   email: 'jiwlee@student.42.fr',
  //   intraUsername: 'jiwlee',
  //   nickname: 'jiwlee',
  //   imagePath: 'https://cdn.intra.42.fr/users/jiwlee.jpg',
  //   status: 'online',
  //   experience: 42,
  //   rankId: 1,
  //   banDate: null,
  //   isStatusPublic: true,
  //   isHistoryPublic: true,
  //   createdAt: '2021-10-11T06:28:44.899Z',
  //   lastModifiedAt: '2021-10-11T06:28:44.899Z',
  //   deletedAt: null,
  // },
  // ]);
}
