import { IUser } from "@/typings/db";
import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<IUser[]>
) {
  res.statusCode = 200;
  res.json([
    {
      userId: 1,
      email: "jiwlee@student.42.fr",
      intraUsername: "jiwlee",
      nickname: "jiwlee",
      imagePath: "/favicon.ico",
      status: "online",
      experience: 42,
      rankId: 1,
      banDate: null,
      isStatusPublic: true,
      isHistoryPublic: true,
      createdAt: "2021-10-11T06:28:44.899Z",
      lastModifiedAt: "2021-10-11T06:28:44.899Z",
      deletedAt: null,
    },
    {
      userId: 1,
      email: "cbaek@student.42.fr",
      intraUsername: "cbaek",
      nickname: "cbaek",
      imagePath: "/favicon.ico",
      status: "online",
      experience: 42,
      rankId: 2,
      banDate: null,
      isStatusPublic: true,
      isHistoryPublic: true,
      createdAt: "2021-10-11T06:28:44.899Z",
      lastModifiedAt: "2021-10-11T06:28:44.899Z",
      deletedAt: null,
    },
    {
      userId: 1,
      email: "kycho@student.42.fr",
      intraUsername: "kycho",
      nickname: "kycho",
      imagePath: "/favicon.ico",
      status: "online",
      experience: 42,
      rankId: 3,
      banDate: null,
      isStatusPublic: true,
      isHistoryPublic: true,
      createdAt: "2021-10-11T06:28:44.899Z",
      lastModifiedAt: "2021-10-11T06:28:44.899Z",
      deletedAt: null,
    },
    {
      userId: 1,
      email: "mykang@student.42.fr",
      intraUsername: "mykang",
      nickname: "mykang",
      imagePath: "/favicon.ico",
      status: "online",
      experience: 42,
      rankId: 4,
      banDate: null,
      isStatusPublic: true,
      isHistoryPublic: true,
      createdAt: "2021-10-11T06:28:44.899Z",
      lastModifiedAt: "2021-10-11T06:28:44.899Z",
      deletedAt: null,
    },
    {
      userId: 1,
      email: "sucho@student.42.fr",
      intraUsername: "sucho",
      nickname: "sucho",
      imagePath: "/favicon.ico",
      status: "offline",
      experience: 42,
      rankId: 5,
      banDate: null,
      isStatusPublic: true,
      isHistoryPublic: true,
      createdAt: "2021-10-11T06:28:44.899Z",
      lastModifiedAt: "2021-10-11T06:28:44.899Z",
      deletedAt: null,
    },
  ]);
}
